version: '3.4'

services:
  db:
    container_name: 'bot_db'
    hostname: 'db'
    image: 'mongo:4.4.2'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo/data:/data/db

  bot:
    container_name: 'bot_bot'
    hostname: 'bot'
    image: 'node:14'
    working_dir: /home/node/bot
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./bot:/home/node/bot
    command: 'npm run start-dev'

  backend:
    container_name: 'bot_backend'
    hostname: 'backend'
    image: 'node:14'
    working_dir: /home/node/backend
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./backend:/home/node/backend
    command: 'npm start'

  # frontend:
  #   container_name: 'bot_frontend'
  #   hostname: 'frontend'
  #   user: 'node'
  #   image: 'node:14'
  #   working_dir: /home/node/frontend
  #   restart: always
  #   ports:
  #     - 8082:8082
  #   volumes:
  #     - ./frontend:/home/node/frontend
  #   command: 'npm start'

volumes:
  mongo-container:
